### ISSUE TITLE
1.20.1

### ISSUE THREAD

**Issue by ItsProfessional** [ahdplayer/NotfiyMe-Fabric#2]

**Comment by ahdplayer** [comment]
I would like to help you but with the new changes to the chat system I don't think I can figure out how to read chat without getting into the weird crypto stuff. Also time is another problem :c

But if you can figure it out I can definitely review your pull request and add it to Modrinth.

**Comment by ItsProfessional** [comment]
Why not like try to read the message off of the chat screen? Haven't checked, but it might be you could just read entries in plaintext by mixing into some function in the chat screen

**Comment by ahdplayer** [comment]
That actually sounds like a great way to do it, I will look into it.
